baseurl = "https://mguegan.github.io/"
languageCode = "en-US"
title = "Matthieu Guegan"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Matthieu Guegan"
  description = "Matthieu Guegan's homepage"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "mguegan"
  Email         = "matthieu@guegan.ch"
  LinkedIn      = "mguegan"
  GnuPG		= "0x09A347D2E262ED58.txt"

## Main Menu
#[[menu.main]]
#  name = "resume"
#  identifier = "resume"
#  weight = 300
#  url = "/resume/"
